import pymongo

# Assuming you have a MongoDB client running locally on default port
client = pymongo.MongoClient("mongodb+srv://surajkumar742494:J9qYedaef8h5WbSg@gym.ftaj8yk.mongodb.net/?retryWrites=true&w=majority&appName=GYM")
database = client["test"]  # Change "your_database_name" to your actual database name
collection = database["exercises"]

# List of exercise names
allExerciseList = [
  {'exerciseName': 'Bench Press (barbell)', 'bodyPart': 'chest', 'equipment': 'barbell'},
  {'exerciseName': 'Squat', 'bodyPart': 'legs', 'equipment': 'barbell'},
  {'exerciseName': 'Deadlift', 'bodyPart': 'full body', 'equipment': 'barbell'},
  {'exerciseName': 'Pull-Up', 'bodyPart': 'back', 'equipment': 'body weight'},
  {'exerciseName': 'Shoulder Press (dumbbell)', 'bodyPart': 'shoulders', 'equipment': 'dumbbell'},
  {'exerciseName': 'Incline Bench Press (barbell)', 'bodyPart': 'chest', 'equipment': 'barbell'},
  {'exerciseName': 'Lateral Raise (dumbbell)', 'bodyPart': 'shoulders', 'equipment': 'dumbbell'},
  {'exerciseName': 'Bicep Curl (dumbbell)', 'bodyPart': 'arms', 'equipment': 'dumbbell'},
  {'exerciseName': 'Leg Press', 'bodyPart': 'legs', 'equipment': 'machine'},
  {'exerciseName': 'Triceps Pushdown (rope)', 'bodyPart': 'arms', 'equipment': 'cable'},
  {'exerciseName': 'Push-Up', 'bodyPart': 'chest', 'equipment': 'body weight'},
  {'exerciseName': 'Lateral Raise (machine)', 'bodyPart': 'shoulders', 'equipment': 'machine'},
  {'exerciseName': 'Bench Press (dumbbell)', 'bodyPart': 'chest', 'equipment': 'dumbbell'},
  {'exerciseName': 'Lat Pulldown (Wide Grip)', 'bodyPart': 'back', 'equipment': 'machine'},
  {'exerciseName': 'Overhead Press (barbell)', 'bodyPart': 'shoulders', 'equipment': 'barbell'},
  {'exerciseName': 'Incline Bench Press (dumbbell)', 'bodyPart': 'chest', 'equipment': 'dumbbell'},
  {'exerciseName': 'Cable Row', 'bodyPart': 'back', 'equipment': 'cable'},
  {'exerciseName': 'Leg Curl', 'bodyPart': 'legs', 'equipment': 'machine'},
  {'exerciseName': 'Bicep Curl (barbell)', 'bodyPart': 'arms', 'equipment': 'barbell'},
  {'exerciseName': 'Chest Fly (dumbbell)', 'bodyPart': 'chest', 'equipment': 'dumbbell'},
  {'exerciseName': 'Triceps Extension (dumbbell)', 'bodyPart': 'arms', 'equipment': 'dumbbell'},
  {'exerciseName': 'Crunches', 'bodyPart': 'core', 'equipment': 'body weight'},
  {'exerciseName': 'Bar Dip', 'bodyPart': 'chest', 'equipment': 'body weight'},
  {'exerciseName': 'Kettlebell Floor Press', 'bodyPart': 'chest', 'equipment': 'kettlebell'},
  {'exerciseName': 'Reverse Flyes (dumbbell)', 'bodyPart': 'back', 'equipment': 'dumbbell'},
  {'exerciseName': 'Hammer Curl', 'bodyPart': 'arms', 'equipment': 'dumbbell'},
  {'exerciseName': 'Barbell Lunge', 'bodyPart': 'legs', 'equipment': 'barbell'},
  {'exerciseName': 'Calf Raise', 'bodyPart': 'legs', 'equipment': 'machine'},
  {'exerciseName': 'Incline Push-Up', 'bodyPart': 'chest', 'equipment': 'body weight'},
  {'exerciseName': 'Rear Delt Row (dumbbell)', 'bodyPart': 'back', 'equipment': 'dumbbell'},
  {'exerciseName': 'Lateral Raise (barbell)', 'bodyPart': 'shoulders', 'equipment': 'barbell'},
  {'exerciseName': 'Bench Press (machine)', 'bodyPart': 'chest', 'equipment': 'machine'},
  {'exerciseName': 'Chest Press (cable)', 'bodyPart': 'chest', 'equipment': 'cable'},
  {'exerciseName': 'Reverse Flyes (machine)', 'bodyPart': 'back', 'equipment': 'machine'},
  {'exerciseName': 'Back Extension', 'bodyPart': 'back', 'equipment': 'machine'},
  {'exerciseName': 'Dumbbell Row', 'bodyPart': 'back', 'equipment': 'dumbbell'},
  {'exerciseName': 'Incline Chest Fly (dumbbell)', 'bodyPart': 'chest', 'equipment': 'dumbbell'},
  {'exerciseName': 'Seated Calf Raise', 'bodyPart': 'legs', 'equipment': 'machine'},
  {'exerciseName': 'Triceps Pushdown (bar)', 'bodyPart': 'arms', 'equipment': 'cable'},
  {'exerciseName': 'Spider Curl', 'bodyPart': 'arms', 'equipment': 'barbell'},
  {'exerciseName': 'Row (barbell)', 'bodyPart': 'back', 'equipment': 'barbell'},
  {'exerciseName': 'Wrist Curl (dumbbell)', 'bodyPart': 'forearms', 'equipment': 'dumbbell'},
  {'exerciseName': 'Face Pull', 'bodyPart': 'back', 'equipment': 'cable'},
  {'exerciseName': 'Butterfly', 'bodyPart': 'chest', 'equipment': 'machine'},
  {'exerciseName': 'Hanging Leg Raise', 'bodyPart': 'core', 'equipment': 'body weight'},
  {'exerciseName': 'Upright Row (barbell)', 'bodyPart': 'shoulders', 'equipment': 'barbell'},
  {'exerciseName': 'Decline Bench Press (dumbbell)', 'bodyPart': 'chest', 'equipment': 'dumbbell'},
  {'exerciseName': 'Pull-Up Against Wall', 'bodyPart': 'chest', 'equipment': 'body weight'},
  {'exerciseName': 'Front Raise (dumbbell)', 'bodyPart': 'shoulders', 'equipment': 'dumbbell'},
  {'exerciseName': 'Lat Pulldown (Close Grip)', 'bodyPart': 'back', 'equipment': 'machine'},
  {'exerciseName': 'Decline Chest Fly (dumbbell)', 'bodyPart': 'chest', 'equipment': 'dumbbell'},
  {'exerciseName': 'Glute Bridge', 'bodyPart': 'legs', 'equipment': 'body weight'},
  {'exerciseName': 'Rear Delt Row (barbell)', 'bodyPart': 'back', 'equipment': 'barbell'},
  {'exerciseName': 'Reverse Flyes (barbell)', 'bodyPart': 'back', 'equipment': 'barbell'},
  {'exerciseName': 'Decline Chest Press (cable)', 'bodyPart': 'chest', 'equipment': 'cable'},
  {'exerciseName': 'Hip Thrust', 'bodyPart': 'legs', 'equipment': 'barbell'},
  {'exerciseName': 'Wood Chop', 'bodyPart': 'core', 'equipment': 'cable'},
  {'exerciseName': 'Hanging Sit Up', 'bodyPart': 'core', 'equipment': 'body weight'},
  {'exerciseName': 'Preacher Curl (dumbbell)', 'bodyPart': 'arms', 'equipment': 'dumbbell'},
  {'exerciseName': 'Bar Dip', 'bodyPart': 'chest', 'equipment': 'body weight'},
  {'exerciseName': 'Decline Bench Press (barbell)', 'bodyPart': 'chest', 'equipment': 'barbell'},
  {'exerciseName': 'Chest Fly (barbell)', 'bodyPart': 'chest', 'equipment': 'barbell'},
  {'exerciseName': 'Rear Delt Row (cable)', 'bodyPart': 'back', 'equipment': 'cable'},
  {'exerciseName': 'Close Grip PushUp', 'bodyPart': 'arms', 'equipment': 'body weight'},
  {'exerciseName': 'Chest Fly (machine)', 'bodyPart': 'chest', 'equipment': 'machine'},
  {'exerciseName': 'Front Raise (barbell)', 'bodyPart': 'shoulders', 'equipment': 'barbell'},
  {'exerciseName': 'Machine Chest Fly', 'bodyPart': 'chest', 'equipment': 'machine'},
  {'exerciseName': 'Shrug (barbell)', 'bodyPart': 'back', 'equipment': 'barbell'},
  {'exerciseName': 'Upright Row (cable)', 'bodyPart': 'shoulders', 'equipment': 'cable'},
  {'exerciseName': 'Pec Deck', 'bodyPart': 'chest', 'equipment': 'machine'},
  {'exerciseName': 'Preacher Curl (barbell)', 'bodyPart': 'arms', 'equipment': 'barbell'},
  {'exerciseName': 'Overhead Press (machine)', 'bodyPart': 'shoulders', 'equipment': 'machine'},
  {'exerciseName': 'Face Pull', 'bodyPart': 'back', 'equipment': 'cable'},
  {'exerciseName': 'Triceps Extension (barbell)', 'bodyPart': 'arms', 'equipment': 'barbell'},
  {'exerciseName': 'Hip Thrust Machine', 'bodyPart': 'legs', 'equipment': 'machine'},
  {'exerciseName': 'Bench Dip', 'bodyPart': 'arms', 'equipment': 'body weight'},
  {'exerciseName': 'Incline Chest Fly (barbell)', 'bodyPart': 'chest', 'equipment': 'barbell'},
  {'exerciseName': 'T Bar Row', 'bodyPart': 'back', 'equipment': 'barbell'},
  {'exerciseName': 'One-Handed Cable Row', 'bodyPart': 'back', 'equipment': 'cable'},
  {'exerciseName': 'One-Handed Lat Pulldown', 'bodyPart': 'back', 'equipment': 'cable'},
  {'exerciseName': 'Push-Up Against Wall', 'bodyPart': 'chest', 'equipment': 'body weight'},
  {'exerciseName': 'Bulgarian Split Squat', 'bodyPart': 'legs', 'equipment': 'dumbbell'},
  {'exerciseName': 'Chin Up', 'bodyPart': 'back', 'equipment': 'body weight'},
  {'exerciseName': 'Decline Chest Fly (barbell)', 'bodyPart': 'chest', 'equipment': 'barbell'},
  {'exerciseName': 'Spider Curl', 'bodyPart': 'arms', 'equipment': 'barbell'},
  {'exerciseName': 'Concentration Curl', 'bodyPart': 'arms', 'equipment': 'dumbbell'},
  {'exerciseName': 'Incline bicep Curl', 'bodyPart': 'arms', 'equipment': 'dumbbell'},
  {'exerciseName': 'Machine Chest Fly', 'bodyPart': 'chest', 'equipment': 'machine'},
  {'exerciseName': 'Shrug (dumbbell)', 'bodyPart': 'back', 'equipment': 'dumbbell'},
  {'exerciseName': 'Muscle-Up (Rings)', 'bodyPart': 'back', 'equipment': 'body weight'},
  {'exerciseName': 'Bench Dip', 'bodyPart': 'arms', 'equipment': 'body weight'},
  {'exerciseName': 'Romanian Deadlift', 'bodyPart': 'legs', 'equipment': 'barbell'},
  {'exerciseName': 'Hack Squat', 'bodyPart': 'legs', 'equipment': 'machine'},
  {'exerciseName': 'Clean', 'bodyPart': 'full body', 'equipment': 'barbell'},
  {'exerciseName': 'Sumo Deadlift', 'bodyPart': 'legs', 'equipment': 'barbell'},
  {'exerciseName': 'Kneeling Incline Push-Up', 'bodyPart': 'chest', 'equipment': 'body weight'},
  {'exerciseName': 'Kneeling Push-Up', 'bodyPart': 'chest', 'equipment': 'body weight'},
  {'exerciseName': 'Push-Ups With Feet in Rings', 'bodyPart': 'chest', 'equipment': 'body weight'},
  {'exerciseName': 'Push-Up Against Wall', 'bodyPart': 'chest', 'equipment': 'body weight'},
  {'exerciseName': 'Push-Up', 'bodyPart': 'chest', 'equipment': 'body weight'},
  {'exerciseName': 'Decline Push-Up', 'bodyPart': 'chest', 'equipment': 'body weight'},
  {'exerciseName': 'Plank', 'bodyPart': 'core', 'equipment': 'body weight'},
  {'exerciseName': 'Hanging Knee Raise', 'bodyPart': 'core', 'equipment': 'body weight'},
  {'exerciseName': 'Cable Crunches', 'bodyPart': 'core', 'equipment': 'cable'},
  {'exerciseName': 'Sit Up', 'bodyPart': 'core', 'equipment': 'body weight'},
  {'exerciseName': 'Standing Calf Raise', 'bodyPart': 'legs', 'equipment': 'machine'},
  {'exerciseName': 'Farmers Walk', 'bodyPart': 'forearms', 'equipment': 'dumbbell'},
  {'exerciseName': 'Wrist Curl (barbell)', 'bodyPart': 'forearms', 'equipment': 'barbell'},
  {'exerciseName': 'Clean and Jerk', 'bodyPart': 'full body', 'equipment': 'barbell'},
  {'exerciseName': 'Muscle Up', 'bodyPart': 'back', 'equipment': 'body weight'},
  {'exerciseName': 'Lat Pulldown (Behind)', 'bodyPart': 'back', 'equipment': 'machine'}
];


# Insert each exercise name into the collection
for exercise_name in allExerciseList:
    exercise_document = {"name": exercise_name['exerciseName'],'body_part': exercise_name['bodyPart'],'equipment': exercise_name['equipment']}
    collection.insert_one(exercise_document)

print("Exercises inserted successfully.")
